### ISSUE TITLE
PHP 5.3 will fail the build

### ISSUE THREAD

**Issue by valendesigns** [xwp/wp-customize-snapshots#1]
5.3 isn't actually broken, the issue is with `PHPCS` complaining about a vendor file. Once that's fixed we can move it out of the `allow_failures` section. I'm going to have to assume that excluding `*/vendor/*` is not doing the job.

``` BASH
No syntax errors detected in vendor/psr/log/Psr/Log/LoggerAwareInterface.php
PHP Parse error:  syntax error, unexpected T_STRING in vendor/psr/log/Psr/Log/LoggerAwareTrait.php on line 8
Parse error: syntax error, unexpected T_STRING in vendor/psr/log/Psr/Log/LoggerAwareTrait.php on line 8
Errors parsing vendor/psr/log/Psr/Log/LoggerAwareTrait.php
```

Important to note that this is something that only happens when you add Coveralls support.

**Comment by westonruter** [comment]
Try adding a `.ci-env.sh` that has:

``` bash
PATH_INCLUDES='*.* php js css tests'
```

That will then restrict the `checked-files` to not include `vendor`: https://github.com/xwp/wp-dev-lib/blob/8798e86c68b3e0c57ebf4f27c8a7f941633cf25c/travis.script.sh#L5-L9

BTW, I realize that `.dev-lib` would be a better config file name than `.ci-env.sh`

**Comment by valendesigns** [comment]
Worked perfectly :+1:
