### ISSUE TITLE
Customize from within Snapshot view fails to load the correct page inside Customizer

### ISSUE THREAD

**Issue by mehigh** [xwp/wp-customize-snapshots#104]
Steps to reproduce:
- customize a page
- hit save
- click on "view on frontend"
- from this page click "Customize"

Issue: 
Although the customized page options are loaded correctly in the sidebar, the iframe content does not reflect the contents of that page.

http://contribute-wp.kbox.site/wp-admin/customize.php?url=http%3A%2F%2Fcontribute-wp.kbox.site%2F%3Fpreview%3Dtrue&page_id=13&autofocus%5Bsection%5D=post%5Bpage%5D%5B13%5D&customize_snapshot_uuid=09db72ba-2750-4ace-8008-71579beb2f66

I URL decoded the parameter passed to customize.php for easier reading:
http://contribute-wp.kbox.site/?preview=true&page_id=13&autofocus[section]=post[page][13]&customize_snapshot_uuid=09db72ba-2750-4ace-8008-71579beb2f66

Video of the issue: https://shrtm.nu/plho

**Comment by mehigh** [comment]
There's a second glitch happening and that's might be related to the above issue.

When editing a page after hitting customize, clicking the 'x' button to close it returns the visitor to the snapshot view  - which is correct from a standard's functionality point of view, as that's the last URL the user was on before getting inside the customizer. 

But, from a usability point of view, it might be a better experience that clicking the 'x' gets the user outside of the customizer & the snapshot view altogether, especially after publishing the changeset.
This needs some dialogue probably. 

I've made a screencast of the different behaviour experienced here:
https://shrtm.nu/5DJS

**Comment by westonruter** [comment]
> Although the customized page options are loaded correctly in the sidebar, the iframe content does not reflect the contents of that page.

Are you sure? Notice how the url contains `preview=true&page_id=13`. This is specifically because you're using Customize Posts which forces non-pretty permalinks to account for a user making changes to the `post_name`.

If the page with ID 13 is not getting loaded in the customizer preview, then this is a different issue, one that I remember happening before and fixing. Do you have the latest version of Customize Posts? Does the issue happen with Customize Posts disabled?

**Comment by mehigh** [comment]
Hmm... You're right. I forgot about that thing although I encountered it a while back -> when discovered that TinyMCE was causing the glitch.
I'll test first with the github version of the two plug-ins and see if the bug is still present, and then try with the customize posts disabled.

**Comment by jeffpaul** [comment]
@mehigh any updates on re-testing this on your end?

**Comment by mehigh** [comment]
5 months later, testing this once more.

**Comment by mehigh** [comment]
This is not an issue without customize posts. I very much like the new and improved bar (publish/save draft/schedule/save pending).

I tested it again with the customize posts plug-in active and again this functions correctly now.
