### ISSUE TITLE
Remember the preview URL and expanded panel/section when saving a changeset

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#107]
When a changeset is made, often the changes specifically relate to a given URL and with a specific panel, section, and control being expanded. It would be ideal if whenever a changeset is saved, that we pass along the current `previewUrl` and any expanded panel/section/control so that these params can then be used in the links generated for “Edit in Customizer” and “Preview ~~Snapshot~~Changeset” as the `url` and `autofocus` params respectively.

This closely relates to [Customizer Browser History](https://github.com/xwp/wp-customizer-browser-history), and this would greatly help with returning to work on a changeset after saving.

![image](https://cloud.githubusercontent.com/assets/134745/21152630/fec1bc0e-c11b-11e6-819a-5488ba01ea27.png)

![image](https://cloud.githubusercontent.com/assets/134745/21152730/7b2547fc-c11c-11e6-8df1-b02bdd4f3255.png)

**Comment by westonruter** [comment]
Let's make this part of 0.6.0. So much for RC1 😄

**Comment by mohdsayed** [comment]
Sure I am working on it. 🙂

**Comment by westonruter** [comment]
Fixed by #129.
