### ISSUE TITLE
Date fields display with error message when selecting non-schedule status

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#112]
Problem:

1. Make change in customizer.
2. Click to Save Draft.
3. Click pencil icon
4. Unexpectedly see date fields and an error message about selecting a future date

I would expect the date fields to only display if I selected “Schedule” intead.

See screenshot:

![image](https://cloud.githubusercontent.com/assets/134745/22837684/762d1594-ef76-11e6-9ccd-80fc84d20e70.png)

This issue seems like it will be resolved if this great mock from @jwold is implemented: https://github.com/xwp/wp-customize-posts/issues/207#issuecomment-278485513

**Comment by mohdsayed** [comment]
I dont remember exactly but it was probably discussed in slack before that a user must add a future date for all status, may be I am wrong but anyways, you are right it should only show the date when the status is future.

Fixed in https://github.com/xwp/wp-customize-snapshots/pull/111
