### ISSUE TITLE
Add UI for listing and accessing current snapshots

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#12]
The custom post type for snapshots should be exposed in the admin so that the existing snapshots can be listed, with links to view them on the frontend or open them in the Customizer. Viewing the edit post screen for a snapshot could show a JSON dump of the settings in the snapshot.

**Comment by valendesigns** [comment]
This still requires a link to view the Snapshot on the front-end before it can be closed.

**Comment by westonruter** [comment]
Link for viewing snapshot on frontend: #49
