### ISSUE TITLE
Check nav menu post reference before garbage collect

### ISSUE THREAD

**Issue by PatelUtkarsh** [xwp/wp-customize-snapshots#133]
Check WP trac ticket: https://core.trac.wordpress.org/ticket/39715

Override core's `delete_post` filter PR https://github.com/xwp/wordpress-develop/pull/224/files
And check for other references(In case of fork/merge snapshot) for `nav_menus_created_posts`'s posts before deleting.

**Comment by westonruter** [comment]
@PatelUtkarsh your patch is now committed to trunk: https://core.trac.wordpress.org/changeset/40676

**Comment by PatelUtkarsh** [comment]
I will start working on PR to fix this issue.
