### ISSUE TITLE
Clicking pending status freezes the browser when user does not have publish capability.

### ISSUE THREAD

**Issue by mohdsayed** [xwp/wp-customize-snapshots#167]
In the new 0.7.0 version, when user does not have publish changeset capability, and only draft and pending appears in status control in publish settings section, clicking the pending option freezes the browser.

**Comment by mohdsayed** [comment]
See ticket https://core.trac.wordpress.org/ticket/42686

**Comment by westonruter** [comment]
@sayedtaqui does this depend on the core fix?

**Comment by westonruter** [comment]
Sorry, I just saw the PR.

**Comment by westonruter** [comment]
Merged #171
