### ISSUE TITLE
Undefined Index displaying Snapshot Details

### ISSUE THREAD

**Issue by terriann** [xwp/wp-customize-snapshots#172]
With [Gutenberg](https://github.com/WordPress/gutenberg/) enabled, combined with WP Customize Snapshot, when in debug mode, errors are displayed on the snapshot detail page

`Notice: Undefined index: title in /Users/Me/Sites/mysite.com/html/wordpress/wp-admin/includes/template.php on line 1042`

## Reproduction Steps
1. Login to WordPress Admin with Gutenberg & WP Customize Snapshots enabled and [debug mode](https://codex.wordpress.org/Debugging_in_WordPress) enabled
2. Schedule new changes in customizer
3. View a changeset snapshot  
4. Observe errors displayed on page

## Screenshots

![screenshot 6](https://user-images.githubusercontent.com/316632/33690026-b3f723f4-daaf-11e7-8dd4-1748dc61f694.png)

## Versions

**Plugins and Theme**

Theme: Custom child theme of Twentyseventeen (only CSS overrides)

WP Customize Snapshots:  0.7.0
Gutenberg: 1.8.1

**Other Version Info**

PHP version: 7.8.1
WordPress: 4.9.1

## Debugging

I haven't seen this error produced anywhere else in admin while using Gutenberg so I thought this would be the best place to report it but the error does not occur when Gutenberg is disabled. Maybe related https://github.com/WordPress/gutenberg/issues/3813?

**Comment by westonruter** [comment]
Fixed in https://github.com/WordPress/gutenberg/pull/3856
