### ISSUE TITLE
Add edit post screen for viewing a snapshot's settings

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#18]
With #12 there would be a list of the available snapshots in the WP Admin post list table. When clicking on a snapshot to access its edit post screen, the settings inside of the snapshot can be listed, along with the values for each. We could also show the current saved values along with the setting values from the snapshot to show a kind of diff view.

Also allow settings to be deleted from a snapshot: #17.

The list of settings in a given snapshot can also be listed from the post list table (#12) when the posts are in expanded view.

**Comment by westonruter** [comment]
This was done in 0.4.0, right?

**Comment by valendesigns** [comment]
Well, that depends on how closely you want to follow the description.

**Comment by westonruter** [comment]
Yeah, I think we can consider this closed.
