### ISSUE TITLE
Allow snapshots to be named

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#19]
When listing snapshots in the admin (#12), the snapshots should be shown with a given name to easily identify what is contained in the snapshot (this would be beyond any settings listed below the snapshot when expanded, as mentioned in #18). 

In addition to a name, we could make use of the `post_excerpt` to capture a “commit message” for a given snapshot.

Alternatively, we could just use the post title as the commit message and not have a separate name field at all.

**Comment by valendesigns** [comment]
I think we should add the ability to modify the title and excerpt. However, we filter the excerpt in the post table to display the modified settings at a glance and adding a commit log in the excerpt would override our ad hoc one, or at the very least append to it. Something to keep in mind.

**Comment by westonruter** [comment]
If we just use the title field alone for the name (commit message) that would probably be simplest.

**Comment by westonruter** [comment]
I think this change would necessitate changing the new “snapshot scheduling” box to be a more general “snapshot properties“ box. In addition to the scheduled date, this box would also have the title (commit message) for the snapshot. The calendar icon could then be replaced with a the edit icon, and the existing edit icon could be replaced with a “pop-out” icon.

<img width="364" alt="customize__wordpress_develops_ _just_another_customizer-driven_site_" src="https://cloud.githubusercontent.com/assets/134745/17614192/2239710e-6019-11e6-8204-d8330536f12f.png">

/cc @PatelUtkarsh

**Comment by PatelUtkarsh** [comment]
@westonruter With this change should we also change the workflow of how one can schedule snapshots?

Currently, On Creation, User first has to save snapshot and then only he can schedule a snapshot in the customizer. 
Calendar icon is not visible when there is no snapshot loaded/created.

**Comment by westonruter** [comment]
@PatelUtkarsh good question. Maybe that could all stay the same, but upon the initial Save the text field would be made available to let them supply a title and re-save to make it stick?

**Comment by PatelUtkarsh** [comment]
![image](https://cloud.githubusercontent.com/assets/5015489/17803609/2238f42a-6615-11e6-8188-df24be127f18.png)
@westonruter @valendesigns New UI, let me know your thoughts :)
