### ISSUE TITLE
New Menus are not being saved to the correct location when you publish a snapshot

### ISSUE THREAD

**Issue by valendesigns** [xwp/wp-customize-snapshots#2]
The menu is being created when the snapshots is published. However, `Menu locations` is not getting checked or updated in the dropdown. Not sure if we need to handle this with JS using something like `wp.customize.bind( 'saved', function () { ... } )` or there is an issue with the data being passed to `customized`.

**Comment by westonruter** [comment]
Is this still an issue?

**Comment by valendesigns** [comment]
Yes it is.

**Comment by miina** [comment]
Additionally, when a new menu is created as part of a snapshot, it won't appear in the Customizer when editing the same snapshot. It will appear when publishing the snapshot but without any added menu items.

**Comment by westonruter** [comment]
It seems then that the `nav_menu_item` controls aren't getting added for items that are only in the Customizer state. The reason could be that the filters that change the `wp_get_nav_menu_items()` aren't getting added or not added early enough? Here is where the filter gets added: https://github.com/xwp/wordpress-develop/blob/45d7737eb29ab381c0cdd4072abbe7e889d7b3b0/src/wp-includes/customize/class-wp-customize-nav-menu-setting.php#L231

Here is where the nav menu items get looped over to add their controls in PHP at Customizer boot time: https://github.com/xwp/wordpress-develop/blob/45d7737eb29ab381c0cdd4072abbe7e889d7b3b0/src/wp-includes/class-wp-customize-nav-menus.php#L576-L596

**Comment by miina** [comment]
Right now there are no filters handling the menu nor the menu items in the Customize Snapshot. Thanks for the hints, looking into it at this moment.
