### ISSUE TITLE
Preview future scheduled snapshots

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#21]
With snapshots being scheduled (#15) there could be multiple snapshots that will have been applied by a given time. There needs to be a way to be able to indicate a future time and preview how the site will appear with all of the future-scheduled snapshots merged together, in order, and applied to the Customizer state.

**Comment by westonruter** [comment]
This is similar to merging multiple snapshots together: #67

**Comment by PatelUtkarsh** [comment]
I can think of two ways of doing this,
- Merge those `future` snapshots together based on input date and create the new snapshot and redirect to its preview, we need to take care of deleting this temporary snapshot once preview is over. 
- Pass some param in URL which can identify previewing schedule snapshot request with a future date. On each request, we need to compute which settings to preview based on input date. We need to take care of ajax request in this case. Also need to insert this extra param on each URL request.

@westonruter thoughts?

**Comment by westonruter** [comment]
The first one, yes. In act, this virtual snapshot can be created with an `auto-draft` status in the same was as changesets are, and they'll then get automatically garbage-collected after a week.
