### ISSUE TITLE
Show conflicts arising with scheduled snapshots

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#22]
When making a change in the Customizer or making a new snapshot, if there is currently one or more scheduled snapshots that touch on a setting that is dirty in the current state, there should be a warning to note of a potential conflict.

See also previewing future scheduled snapshots: #15 & #21

**Comment by PatelUtkarsh** [comment]
@westonruter On which action Should we trigger the warning? 
- On snapshot save/update/schedule
- New Action to check for conflicts before

Also, It's warning so we are allowing to save snapshot even though snapshot conflicts with other, Probably Yes?

Also, In the case of large number draft/scheduled snapshot this will be slow as we need to go through all snapshot (as`'posts_per_page' => -1`)

**Comment by westonruter** [comment]
@PatelUtkarsh 

The warning should probably appear once make a change to a setting. So let's say you've scheduled a change to `blogname`. If you go in and make a change to the Site Title, this could then result in an Ajax request to find any future-scheduled snapshots that contain the `blogname` setting. If there are, then the warning could be shown (perhaps an ⚠️ icon that opens a lightbox that lists out the snapshots that contain the setting along with each future value for the setting displayed in the lightbox). 

So this means that for every control in the Customizer, the first time that one of its associated setting(s) gets changed, there would be one Ajax request to obtain the future snapshot values.

> Also, It's warning so we are allowing to save snapshot even though snapshot conflicts with other, Probably Yes?

Yes. If the value conflicts with a future scheduled snapshot, then this should not block the save. By contrast, if someone else had the Customizer open and saved a different value concurrently, then this _would_ result in validation block, both if the setting's value was published _and_ if the setting's value was saved to a snapshot that someone else is also editing. This is out of scope for this ticket, however. It is the focus of #60.

> Also, In the case of large number draft/scheduled snapshot this will be slow as we need to go through all snapshot (as `'posts_per_page' => -1`)

Not snapshots with `draft`, I don't think. I think we should perhaps only consider snapshots with `pending` or `future` statuses. If we do consider `draft` snapshots as well, then these should have a “less-severe” conflict warning, so a notice instead of a warning. There can be snapshots that are made that are never intended to be published. In any case, having '`posts_per_page` => -1' makes sense. 

_Another idea:_ For doing performant lookups of snapshots that contain a given setting, how about we create a new private taxonomy? When a snapshot is saved, it can iterate over the settings in the snapshot and ensure a term in this taxonomy exists for each, using a term `name` corresponding to the setting ID. Then each of these terms can be associated with the snapshot post. So then you can do a simple `tax_query` to look up all snapshot posts that contain a given setting!

**Comment by PatelUtkarsh** [comment]
@westonruter 
Private Taxonomy for performance:
I like the idea but wouldn't that be too many terms to search on? 

For example `postmeta[post][24][custom_post_meta]` If we were not storing `post_id` 24 in setting id the max terms would have been small but as we are storing it there would be so many possible terms with each post-type.

If we go this way we also need to make sure we destroy terms if it is not being used when the snapshot is being published.

**Comment by westonruter** [comment]
It's true, there would eventually be a lot of terms, likely on the order of 10 terms per snapshot. So as the number of snapshots grow, there'd be 10x terms for the number of snapshots, approximately. For a post, there would be a term for `post[post][24]` and for `postmeta[post][24][_thumbnail_id]`. Since these are dynamic settings, there would be no limit to these. For statically-registered settings, like `blogname` there would be a limit.
