### ISSUE TITLE
Save & Activate button is missing

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#28]
When doing a live preview of a theme switch, the Save & Activate button is hidden entirely.

**Comment by valendesigns** [comment]
That is because Snapshots doesn't support theme switching yet.

**Comment by westonruter** [comment]
But then shouldn't Snapshots be disabled entirely in this context rather than disabling the Save button?

**Comment by valendesigns** [comment]
That would likely be the correct path until it's fully supported. I didn't try to make theme switching work as it wasn't a requirement for the first iteration.
