### ISSUE TITLE
Add support for translations with load_plugin_textdomain

### ISSUE THREAD

**Issue by valendesigns** [xwp/wp-customize-snapshots#3]
As well, add the Grunt tasks that connect with [Transifex](https://www.transifex.com) for auto generating language files during the `build` task. Using this service will allow the community to translate the plugin without creating pull requests.
- [x] Transifex project & Grunt task
- [ ] Integrate `load_plugin_textdomain`

**Comment by valendesigns** [comment]
I've added the Grunt task that connects to Transifex with both push and pull commands, the only thing left is to transfer ownership of the project to XWP. @westonruter you'll need to create a free account at Transifex and let me know when it's ready so I can send the request.

**Comment by westonruter** [comment]
@valendesigns isn't a service like Transifex now irrelevant that WordPress.org is rolling out language packs to all plugins? See https://make.wordpress.org/plugins/2015/09/01/plugin-translations-on-wordpress-org/

**Comment by valendesigns** [comment]
I guess so after reading that. Does this mean we remove the .pot file too?

**Comment by valendesigns** [comment]
I'm a little confused how `load_plugin_textdomain` is going to work with language packs that don't get installed into the plugins `/languages/` directory.

**Comment by westonruter** [comment]
I'm utterly inexperienced with what the new language packs mean, but I _think_ it means we don't need the POT file. I recall the textdomain _must_ be the plugin slug, e.g. `customize-snapshots`, so that it can locate the installed languages in the location where language packs are installed (not in a subdirectory of the plugin itself).

**Comment by valendesigns** [comment]
I'm not sure how it all works now either. I guess removing it for now it probably best, which, I've done.
