### ISSUE TITLE
Snapshot UUID should be stripped from the URL and JS state once published

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#37]
Once a snapshot is published, it should be considered frozen and a new one should be started. By stripping the UUID from the URL, this will help ensure that a user doesn't inadvertently go back to a snapshotted Customizer and not get the latest changes to modify.

**Comment by westonruter** [comment]
Likewise, the “Update” button should go back to a “Save” button once Publish has happened.

**Comment by valendesigns** [comment]
I'm working on this real quick.
