### ISSUE TITLE
Allow a snapshot to be copied/forked

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#41]

**Comment by PatelUtkarsh** [comment]
@westonruter When we say forked should the original post remember it's forked snapshots? (If original posts remember it's child forks then every child will need to remember it's parent as when we delete a post we need to clear that id.) 

Would there be UI that says these snapshots are forked from currently viewing snapshot? (maybe a metabox?)

Also, this will show conflicts with forked snapshot #71, Should we ignore fork conflict?

**Comment by westonruter** [comment]
@PatelUtkarsh good question. I think we could leverage the `post_parent` field to capture the relationship between a forked snapshot and its original snapshot. If the parent gets deleted then the ID will either point to nothing or a trashed post, which should have the same result: the parent should be considered empty.

There could be a UI that shows snapshots that lists out the snapshots that were forked from a given snapshot (any post which has a `post_parent` matching the current post), and showing the snapshot that it was forked from (the `post_parent`, if any).

Good question on whether conflicts should be shown when they are related as a fork. I'm guessing so, but since `draft` is no longer included among the snapshots to consider I think this is fine. I think it would be unlikely to fork a `pending` or `future` snapshot. In fact, maybe forking should be disabled when the snapshot is in a non-`draft` state.

**Comment by PatelUtkarsh** [comment]
@westonruter what would be the UI for showing forked snapshot meta-box?

**Comment by westonruter** [comment]
@PatelUtkarsh not sure. But perhaps it could be tied into the Revisions metabox. In addition to the revisions of that specific snaphot, it could have sections that list the forked snapshots as well as the parent snapshot (if any).

**Comment by PatelUtkarsh** [comment]
Revisions box will only display if the post has revisions and I couldn't find any hook that we can tie our template in.
Current UI: #90 
![image](https://cloud.githubusercontent.com/assets/5015489/18272029/1c2bcee4-7453-11e6-8bd2-48b2c1aca57e.png)

**Comment by PatelUtkarsh** [comment]
@westonruter Should we go with `Fork` word only? Currently we are using `fork/copy` as button and metabox title.

@sayedwp any input on above UI?

**Comment by westonruter** [comment]
“Clone” or “Duplicate” would also work. But I think “Fork” works well for now since it has a distinct history that would not be entailed by other words.

**Comment by jeffpaul** [comment]
@westonruter & @PatelUtkarsh it looks like we're limiting the forking to only drafted snapshots. Assuming that was a conscious decision, should we add a tooltip or note on scheduled/trashed/published snapshots to note they're unable to be forked? Or should we expanding forking to include those other snapshot states?

**Comment by westonruter** [comment]
@jeffpaul Good question. Maybe in the cases where it cannot be forked, the button can be there but `disabled` (with a tooltip)? I suppose forking should actually be allowed for `pending` snapshots as well. Just trying to think about the user flow. If a snapshot is `future` or `publish` the snapshot should be essentially considered locked-in, and making a fork of it would seem strange because the values are already live or are on their way to being live? Maybe this isn't a problem, and in some cases maybe you'd _want_ to fork a previously-published snapshot as a way to restore the settings that were published at that time. (Though, see also #20 for a more dedicated way to revert a snapshot.) So yeah, maybe we should remove the restrictions on which snapshots statuses can be forked.

**Comment by PatelUtkarsh** [comment]
@westonruter If we are removing the restrictions on which snapshot statuses can be forked, All forked snapshot should be assigned post-status as `draft`?

**Comment by westonruter** [comment]
@PatelUtkarsh yes. That sounds right.
