### ISSUE TITLE
Eliminate storage of non-dirty settings

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#42]
I think I know why I was having environment problems yesterday. I think it was because I had so many settings loaded into the Customizer (278) and many of the settings were large being post settings with potentially very large `post_content`. I just looked at a snapshot I made and I calculated its size at 76,170 bytes (via `wp post get 305 --field=post_content | wc -c`). This is _large_. The `post_content` field is a `LONGTEXT` in MySQL which means it can store a snapshot `post_content` that is 56,386 times larger. Nevertheless, this is a ton of data to be passing back and forth with each snapshot update, and it could get is into trouble with timeouts and network latency.

I think we should perhaps remove the `full` scope from being a feature for the sake of scalability. With the UX changes in #30 it's not even an option anymore in the UI, and I think that it has always been a bit dubious in its usefulness. Thoughts?

**Comment by valendesigns** [comment]
I think that would be sane, and I'm all for it.

**Comment by westonruter** [comment]
@valendesigns is this something you had a branch for which you want to include in 0.4.0?

**Comment by valendesigns** [comment]
It's already in 0.4.0 I merged the branch locally.

**Comment by westonruter** [comment]
I've some followup in #46.

**Comment by valendesigns** [comment]
I've not tested it but that change looks like it's reverting things. Wouldn't it now add all the settings again, regardless of if their dirty?

**Comment by westonruter** [comment]
@valendesigns oh, possibly. I assumed that the JS wasn't sending the non-dirty settings in the request, but maybe this wasn't done?
