### ISSUE TITLE
Make attachments atomic until a transaction is published

### ISSUE THREAD

**Issue by frankiejarrett** [xwp/wp-customize-snapshots#44]
### Current behavior

When you upload attachments via the Customizer they are:
1. Added to the filesystem.
2. Saved to the database as a new post.
3. Immediately visible to all other logged in users in the Media Library.
### Desired behavior

Attachments that are uploaded _within_ a Customizer session should not be published, or even visible by other logged in users, until the user decides to **publish** the transaction.
### Possible idea

Until a transaction is published, all `attachment` posts that have been uploaded inside the Customizer have their post status set to `auto-draft` rather than `inherit`. This will make them invisible inside the Media Library from other logged in users.

All `attachment` posts uploaded while in the Customizer can be stored somehow inside the transaction.

``` json
"attachments": {
    "value": [12,13,14]
}
```

**Disclaimer:** I'm not at all familiar with the schema, so this is probably wrong, but hopefully the concept makes sense.

If you are in the Customizer session, perhaps `pre_get_posts` could be used to allow these `attachment` IDs to be visible in the Media Library just for you?
### Publish or Discard

If a transaction is **published**, then the post status on these `attachment` IDs can be set to `inherit`, making them visible inside in the Media Library like normal.

If a transaction is **discarded**, then the `attachment` IDs can be force deleted via `wp_delete_attachment( $ID, true )` which will not only delete them from the database, but also from the filesystem.

**Comment by westonruter** [comment]
@fjarrett thanks for the report. Nevertheless, I think actually this is outside the scope of the Customize Snapshots plugin. It's actually a deeper issue in Core itself where the Media Library JS is not Customizer-aware. Beyond uploading new attachments, there is also the issue whereby if you edit an attachment's fields (e.g. title or caption) then these changes get saved immediately as soon as you blur the field. All of these changes need to be added to the Customizer state to then be persisted if the user hits Save & Publish. If this is done, then snapshots would automatically capture the state and be able to persist it in the same way it does for Customize Posts. So I don't think this is an issue for Customize Snapshots specifically, but rather an issue that needs to be opened in Core.

**Comment by frankiejarrett** [comment]
@westonruter OK cool, I wondered this after a posted it here. Thanks for clearing that up, I'll report this in Trac instead.
