### ISSUE TITLE
Add admin bar link to view snapshot edit post screen

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#48]
In addition to the Customize link opening the snapshot in the Customizer, there should also be an easy way to access the Snapshot edit post screen from the frontend, if browsing the site in a snapshot state (see #47).

**Comment by miina** [comment]
Should this go to admin bar only or to the Customizer as well? E.g. to the Customize Controls section.

**Comment by valendesigns** [comment]
There isn't a UI built in the Customizer yet for managing Snapshots. This ticket is specifically to address the admin bar link only.
