### ISSUE TITLE
Handle case where user lacking some setting caps loads a snapshot into the Customizer

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#58]
If a snapshot is saved that contains modified settings that require `edit_theme_options` and yet a user opens this snapshot in the Customizer and they lack this capability, the setting will effectively get dropped from the snapshot if they try saving. I see two options here:
- Block a user from being able to load a snapshot when they lack all caps for the settings in it.
- When a user with insufficient caps saves settings that are coming from a snapshot, ensure that all settings from the snapshot get loaded and forcibly saved along with the settings the user actually submitted in the request.

The first option would be easier and would be more expected.

**Comment by westonruter** [comment]
This should be addressed by changesets. A changeset UUID is always supplied when accessing the preview and all pre-saved settings in the changeset should be made available in the preview, even though the user cannot modify them (write them into the changeset).

**Comment by jeffpaul** [comment]
@westonruter So this _should_ be resolved via #102?

**Comment by westonruter** [comment]
@jeffpaul I believe so. Just needs testing to confirm.

**Comment by PatelUtkarsh** [comment]
@westonruter Tested and it works as expected. The user can load changeset and make changes to the section which is accessible to it, other section data preserve on save of that. 

Created snapshot with a user A who doesn't have access to some section and added some data, Added new data in changeset with User B(admin) of which user A doesn't have access to, Opened changeset with user A and edited/updated new data, It preserves user B's changes in changeset.
CC: @jeffpaul.
