### ISSUE TITLE
Allow multiple snapshots to be merged into a single snapshot

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-snapshots#67]
Inverse of #16.

Probably should create a new snapshot post post that contains the merged settings from the other snapshots. We could use bulk actions to implement this.

**Comment by westonruter** [comment]
We could potentially trash the snapshots that are merged into the single snapshot. This would also entail preventing snapshots that are published or pending from being available for merging.

**Comment by kienstra** [comment]
Hi @westonruter,
Would there be a way to handle conflicting settings in merged snapshots?

**Comment by westonruter** [comment]
@kienstra great question. I suppose so! I guess there would need to be an intermediate step where any conflicts are resolved.

**Comment by PatelUtkarsh** [comment]
@westonruter Should we allow `schedule` snapshot to be merged?

**Comment by PatelUtkarsh** [comment]
Also, If a user selects 2 publish and one draft for merge we will show error, but in the case of 1 publish and 2 drafts, Should we process with the merge of 2 draft and show error or just display error without merging it?

**Comment by westonruter** [comment]
@PatelUtkarsh Yes. I see no reason why a scheduled or even a published snapshot should not be able to be merged. You should be able to include published snapshots in the merges in the same way that you should be able to duplicated/forked (#41). This is closely related to allowing a snapshot to be reverted (#20): consider publishing a snapshot, making some changes, and then wanting to restore the site to a previous state. This could be done by duplicating a previously-published snapshot, or selecting multiple snapshots to merge together to create such a “revert” snapshot.
