### ISSUE TITLE
Disable editing slug from Quick Edit

### ISSUE THREAD

**Issue by miina** [xwp/wp-customize-snapshots#98]
Currently the `slug` of a Snapshot is editable from the Quick Edit action link on `wp-admin/edit.php?post_type=customize_snapshot` page. Since it's the UUID, it shouldn't be editable.

**Comment by westonruter** [comment]
You're absolutely right.

**Comment by PatelUtkarsh** [comment]
Should we completely block quick-edit?

**Comment by westonruter** [comment]
Yes.
